### ISSUE TITLE
What is the canonical URL for these schemas?

### ISSUE THREAD

**Issue by pudo** [openc/openc-schema#21]
They're pretty cool, I'd like to use them in a project - but would need to either copy them or have a public url. Perhaps even just having a gh-pages branch on this repo would be enough?

**Comment by CountCulture** [comment]
By public URL, do you mean human readable version as opposed to public github repo?

**Comment by pudo** [comment]
Yeah something that's stable. Are you using the raw links at the moment? Could do that, too.

**Comment by CountCulture** [comment]
Yup. We're using this repo as a submodule in several other repos

**Comment by jpmckinney** [comment]
@pudo Is there any value-added by having the URL not be e.g. https://raw.githubusercontent.com/openc/openc-schema/master/schemas/company-schema.json ?

I suppose having the correct content-type would be nice, but not sure if that's a compelling reason.

**Comment by jpmckinney** [comment]
On the other hand, I suppose we could rename `master` to `gh-pages` and add a `CNAME` file, and nothing dramatic would happen.

**Comment by jpmckinney** [comment]
I'm now planning on using gh-pages for another purpose. Anyhow, I'm not hearing opposition to using githubusercontent.com URLs.
