### ISSUE TITLE
date should be valid for retrieved_at

### ISSUE THREAD

**Issue by CountCulture** [openc/openc-schema#37]
@inglesp seems to required a date-time, but sometimes we only have a date (for example if it's the export date of one of many historic files on FTP site)

**Comment by jpmckinney** [comment]
Aren't the semantics of "retrieval" different from "export"? To me, "retrieved at" is whenever the source document was retrieved. I guess the issue is what to do in case that source document is a secondary source instead of a primary source (in which case, the "retrieved at" of the primary source may be unknown).

**Comment by CountCulture** [comment]
@jpmckinney This is part of the somewhat confusing terminology about dates in the OC system that we need to get solved. There's a discussion somewhere that @sebbacon can prob point to (here: https://app.asana.com/0/search/77078247974337/27943046004743 ? ), but basically we are overloading/have ambiguous names for attributes.

retrieved_at in the company table/model is either the date(time) we retrieved it, or if there is a clear and genuine proxy the date(time) that proxy got the data. An example of such a proxy is for example, periodic data dumps produced by the government. We use the retrieved_at internally when combining data from different sources to determine which has precedence when, for example, updating a company name. So the monthly data dumps by Companies House allowed us to ensure all the company names were refreshed, updating those companies we hadn't retrieved for some time, but not those that we had retrieved since the date of the dump.

Given we often only know about the date of such dumps, it doesn't really make sense to require them to be date times, particularly as we don't internally in the model.

**Comment by jpmckinney** [comment]
Doesn't sample_date have the desired semantics? It's a date on which we know the fact to be true / on which some source publishes it as being true.

**Comment by CountCulture** [comment]
a) we don't have sample date for companies
b) we've come to the conclusion that sample_date is misleading and that's
part of the reason for wanting to review the whole thing.

This issue was mainly to bring the schema validation in line with existing
behaviour.

On 4 January 2016 at 15:22, James McKinney <notifications@github.com> wrote:

> Doesn't sample_date have the desired semantics? It's a date on which we
> know the fact to be true / on which some source publishes it as being true.
>
> Sent from mobile
>
> > On Jan 4, 2016, at 8:14 AM, CountCulture <notifications@github.com>
> wrote:
> >
> > @jpmckinney This is part of the somewhat confusing terminology about
> dates in the OC system that we need to get solved. There's a discussion
> somewhere that @sebbacon can prob point to (here:
> https://app.asana.com/0/search/77078247974337/27943046004743 ? ), but
> basically we are overloading/have ambiguous names for attributes.
> >
> > retrieved_at in the company table/model is either the date(time) we
> retrieved it, or if there is a clear and genuine proxy the date(time) that
> proxy got the data. An example of such a proxy is for example, periodic
> data dumps produced by the government. We use the retrieved_at internally
> when combining data from different sources to determine which has
> precedence when, for example, updating a company name. So the monthly data
> dumps by Companies House allowed us to ensure all the company names were
> refreshed, updating those companies we hadn't retrieved for some time, but
> not those that we had retrieved since the date of the dump.
> >
> > Given we often only know about the date of such dumps, it doesn't really
> make sense to require them to be date times, particularly as we don't
> internally in the model.
>
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openc/openc-schema/issues/37#issuecomment-168704643>.
>



-- 
-------------------------------------------------------
OpenCorporates :: The Open Database of the Corporate World
http://opencorporates.com
OpenlyLocal :: Making Local Government More Transparent
http://openlylocal.com
Blog: http://countculture.wordpress.com
Twitter: http://twitter.com/CountCulture

**Comment by jpmckinney** [comment]
Shall I create a PR changing the format of `retrieved_at` from `date-time` to `date`?

My understanding is `date` is a superset of `date-time` - otherwise, I can do a `oneOf` with each format as options (since JSON Schema doesn't support an array for `format`).

**Comment by CountCulture** [comment]
Yes please. I can as long as we include both types in a spec case, it
doesn't matter whether we use date or oneOf

On 25 January 2016 at 14:18, James McKinney <notifications@github.com>
wrote:

> Shall I create a PR changing the format of retrieved_at from date-time to
> date?
>
> My understanding is date is a superset of date-time - otherwise, I can do
> a oneOf with each format as options (since JSON Schema doesn't support an
> array for format).
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openc/openc-schema/issues/37#issuecomment-174520772>.
>



-- 
-------------------------------------------------------
OpenCorporates :: The Open Database of the Corporate World
http://opencorporates.com
OpenlyLocal :: Making Local Government More Transparent
http://openlylocal.com
Blog: http://countculture.wordpress.com
Twitter: http://twitter.com/CountCulture
