### ISSUE TITLE
Consider adding nationality or national_identity to person

### ISSUE THREAD

**Issue by jpmckinney** [openc/openc-schema#42]
FR BODACC stores the nationality ("nationalité" or `nationnalite` (sic) in XSD) of a person (`française`, `haïtienne`, etc.), e.g. http://www.bodacc.fr/annonce/detail/BXA14363000418A

**Comment by CountCulture** [comment]
Yes, let's do this. We already have this in OC for officers.
By the way on that notice, is it clear to you what is being sold - company?
'business'? property?

**Comment by jpmckinney** [comment]
See #43 

I interpret as this entity:

```
 n°RCS :
    424 058 105 RCS Sarreguemines 
Nom :
    SCHAEFFER	
Prénom :
    Jean-François
```

bought this property:

```
Etablissement(s) :

    Origine du fond :
        Etablissement secondaire acquis par achat au prix stipulé de 95 000 euros
    Activité :
        dépôt de pain, salon de thé
    Adresse de l'établissement :
        132 rue de la Gare 57150 Creutzwald 
```

which was previously owned by:

```
n°Identification :
    521 871 210 RCS Sarreguemines 
Dénomination :
    LES PETITS FOURS DE VALERIE
```

**Comment by CountCulture** [comment]
OK. So we're talking about property here, or at least a 'business' (given the activity description) rather than a company. Wonder what happens when a company is sold -- potentially gives us shareholder or parent company info? Still we can investigate when we've got the data in OC/OG

**Comment by jpmckinney** [comment]
The `etablissement` block is in RCS-A only, and the previous operators/owners blocks are sometimes a real person, so I don't think it's ever about purchase of companies - just properties.

**Comment by jpmckinney** [comment]
https://fr.wikipedia.org/wiki/Fonds_de_commerce
